@startuml

[*] --> Idle

Idle: Ожидание команды

Idle --> Adding: Добавить
Idle --> Selling: Продать билет
Idle --> Binding: Привязать постановку
Idle --> Viewing: Информация
Idle --> Saving: Сохранить
Idle --> Loading: Загрузить
Idle --> Repetitions: Репетиции


state Adding {
    [*] --> EnterData
    EnterData --> Create
    Create --> [*]
}

state Selling {
    [*] --> Select
    Select --> Confirm
    Confirm --> [*]
}

state Binding {
    [*] --> Select
    Select --> Generate
    Generate --> [*]
}

state Viewing {
    [*] --> Display
    Display --> [*]
}

state Saving {
    [*] --> Write
    Write --> [*]
}

state Loading {
    [*] --> Read
    Read --> Restore
    Restore --> [*]
}

state Repetitions {
    [*] --> Manage
    Manage --> [*]
}


Adding --> Idle
Selling --> Idle
Binding --> Idle
Viewing --> Idle
Saving --> Idle
Loading --> Idle
Repetitions --> Idle

Idle --> [*]: Выход


@enduml
